language: node_js
node_js:
  - 12

# Docker integration
services:
  - docker

# Pre-testing installs
install:
  - npm ci

# Scripts to be run such as tests
before_script:
  - npm run lint
  - echo "no tests without UI"

script:
  - docker --version # print the version for logging
  - docker build . -t udagram-image-frontend
  - docker tag udagram-image-frontend fgaviria/udagram-image-frontend:latest

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push fgaviria/udagram-image-frontend
